server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  cloud:  # 连接远程git仓库
    config:
      server:
        git:
          uri: https://gitee.com/HSCZF/springcloud.git      # 是 https，不是 git

# 通过config-server 可以连接到git 访问其中的资源以及配置