server:
  port: 9527

# spring
spring:
  application:
    name: springcloud-zuul

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true

# info配置
info:
  app.name: czf-springcloud
  company.name: blog.czf.com

# zuul配置
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept  # 要和provider的spring.application.name:springcloud-provider-dept 要一致
    mydept.path: /mydept/**
  ignored-services: "*"   # 不能使用这个路径访问了，忽略，隐藏全部的源路径，写springcloud-provider-dept这个只能隐藏这个
  prefix: /czf            # www.czf.com，设置公共的前缀
